### ISSUE TITLE
Tried to install in M1 mac - got an error

### ISSUE THREAD

**Issue by not-that-nda** [K-410/textension#6]
Here is the console printout I get when trying to enable:

Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/modules/addon_utils.py", line 369, in enable
    mod.register()
  File "/Users/ndeandres/Library/Application Support/Blender/3.6/scripts/addons/textension/utils.py", line 312, in wrapper
    ret = func(*args, **kw)
  File "/Users/ndeandres/Library/Application Support/Blender/3.6/scripts/addons/textension/__init__.py", line 31, in register
    overrides.init()
  File "/Users/ndeandres/Library/Application Support/Blender/3.6/scripts/addons/textension/overrides/__init__.py", line 178, in init
    assert runtime.active_overrides == 0
AssertionErro

**Comment by K-410** [comment]
Hi

Textension overrides internal operators when the addon is enabled. The error tells me that the addon was enabled while there still was overrides active, which means that a prior error caused the addon to not be fully unregistered.

Please check the console for any errors that occurred *before* the one you posted, as that's the real problem.

**Comment by not-that-nda** [comment]
Yes, failed the first time and tried again.

Below an attempt to activate it right after blender loads:

Traceback (most recent call last):
  File "/Users/ndeandres/Library/Application Support/Blender/3.6/scripts/addons/textension/utils.py", line 312, in wrapper
    ret = func(*args, **kw)
  File "/Users/ndeandres/Library/Application Support/Blender/3.6/scripts/addons/textension/__init__.py", line 32, in register
    ui.init()
  File "/Users/ndeandres/Library/Application Support/Blender/3.6/scripts/addons/textension/ui/__init__.py", line 13, in init
    gl.init()
  File "/Users/ndeandres/Library/Application Support/Blender/3.6/scripts/addons/textension/ui/gl.py", line 22, in init
    Rect.shader = gpu.types.GPUShader(rct_vert, rct_frag)
Exception: Shader Compile Error, see console for more details
Exception in module register(): /Users/ndeandres/Library/Application Support/Blender/3.6/scripts/addons/textension/__init__.py
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/3.6/scripts/modules/addon_utils.py", line 369, in enable
    mod.register()
  File "/Users/ndeandres/Library/Application Support/Blender/3.6/scripts/addons/textension/utils.py", line 312, in wrapper
    ret = func(*args, **kw)
  File "/Users/ndeandres/Library/Application Support/Blender/3.6/scripts/addons/textension/__init__.py", line 32, in register
    ui.init()
  File "/Users/ndeandres/Library/Application Support/Blender/3.6/scripts/addons/textension/ui/__init__.py", line 13, in init
    gl.init()
  File "/Users/ndeandres/Library/Application Support/Blender/3.6/scripts/addons/textension/ui/gl.py", line 22, in init
    Rect.shader = gpu.types.GPUShader(rct_vert, rct_frag)
Exception: Shader Compile Error, see console for more details

**Comment by K-410** [comment]
Thanks, is there anything more?

I can see there's a Shader Compile Error, but the error text is cut right before it's supposed to tell us the reason.

**Comment by not-that-nda** [comment]
I start blender from the terminal, despite what the message seems to suggest that is the terminal text copy pasted from it directly. It says to check the terminal but that is all the information from it.

Below a copy paste from install, and try to activate in a 3.6 vanilla blender almost barebone:
addon_utils.disable: textension not disabled
Modules Installed (textension) from '/Users/ndeandres/Downloads/textension.zip' into '/Applications/BlenderDev.app/Contents/Resources/3.6/scripts/addons'
/Applications/BlenderDev.app/Contents/Resources/3.6/scripts/addons/textension/core.py:33: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if line[end - 1] is "\\":
/Applications/BlenderDev.app/Contents/Resources/3.6/scripts/addons/textension/core.py:104: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif c is "#":
/Applications/BlenderDev.app/Contents/Resources/3.6/scripts/addons/textension/prefs.py:313: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if plugin_draw_func and active_plugin is not "none":
/Applications/BlenderDev.app/Contents/Resources/3.6/scripts/addons/textension/ui/widgets.py:1185: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if index is not -1:
/Applications/BlenderDev.app/Contents/Resources/3.6/scripts/addons/textension/overrides/default.py:306: SyntaxWarning: "is" with a literal. Did you mean "=="?
  wrap = column is 0
Traceback (most recent call last):
  File "/Applications/BlenderDev.app/Contents/Resources/3.6/scripts/addons/textension/utils.py", line 312, in wrapper
    ret = func(*args, **kw)
  File "/Applications/BlenderDev.app/Contents/Resources/3.6/scripts/addons/textension/__init__.py", line 32, in register
    ui.init()
  File "/Applications/BlenderDev.app/Contents/Resources/3.6/scripts/addons/textension/ui/__init__.py", line 13, in init
    gl.init()
  File "/Applications/BlenderDev.app/Contents/Resources/3.6/scripts/addons/textension/ui/gl.py", line 22, in init
    Rect.shader = gpu.types.GPUShader(rct_vert, rct_frag)
Exception: Shader Compile Error, see console for more details
Exception in module register(): /Applications/BlenderDev.app/Contents/Resources/3.6/scripts/addons/textension/__init__.py
Traceback (most recent call last):
  File "/Applications/BlenderDev.app/Contents/Resources/3.6/scripts/modules/addon_utils.py", line 369, in enable
    mod.register()
  File "/Applications/BlenderDev.app/Contents/Resources/3.6/scripts/addons/textension/utils.py", line 312, in wrapper
    ret = func(*args, **kw)
  File "/Applications/BlenderDev.app/Contents/Resources/3.6/scripts/addons/textension/__init__.py", line 32, in register
    ui.init()
  File "/Applications/BlenderDev.app/Contents/Resources/3.6/scripts/addons/textension/ui/__init__.py", line 13, in init
    gl.init()
  File "/Applications/BlenderDev.app/Contents/Resources/3.6/scripts/addons/textension/ui/gl.py", line 22, in init
    Rect.shader = gpu.types.GPUShader(rct_vert, rct_frag)
Exception: Shader Compile Error, see console for more details

**Comment by K-410** [comment]
That's interesting.

What semantic version of Blender are you running? I need the three numbers eg. (3, 6, 0) from typing `bpy.app.version` in Blender's interactive console. It might be that you're running a version incompatible with Textension.

**Comment by not-that-nda** [comment]
(3, 6, 0)

**Comment by K-410** [comment]
Are you able to run this in the text editor without any errors?

This uses the 3.3.0+ shader creation api in Blender to make the shader gpu backend-agnostic.

```python
import gpu


def create_rect_shader_330_plus():
    info = gpu.types.GPUShaderCreateInfo()
    typedefs = """
    struct RectColors {
        vec4 background_color;
        vec4 border_color;
    };

    const vec4 data[4] = {
        {-1.0, -1.0, 0.0, 1.0},
        { 1.0, -1.0, 0.0, 1.0},
        { 1.0,  1.0, 0.0, 1.0},
        {-1.0,  1.0, 0.0, 1.0},
    };
    """
    info.typedef_source(typedefs)
    info.fragment_out(0, "VEC4", "fragColor")
    info.uniform_buf(0, "RectColors", "colors")
    info.push_constant("VEC4", "rect")
    info.push_constant("VEC4", "shadow")
    info.push_constant("VEC2", "shadow_offset")
    info.push_constant("FLOAT", "corner_radius")
    info.push_constant("FLOAT", "border_width")
    info.vertex_source("""
    void main() {
        gl_Position = data[gl_VertexID];
    };
    """)
    info.fragment_source("""
    float rbox(vec2 center, vec2 size, float r) {
        vec2 q = abs(center) - size + r;
        return min(max(q.x, q.y), 0.0) + length(max(q, 0.0)) - r;
    }

    void main() {
        vec4 final = colors.background_color;
        float bw   = border_width;
        
        vec4 shadow_final = mix(vec4(0.0), shadow, shadow.a);
        vec4 border_color = mix(final, colors.border_color, colors.border_color.a * min(1.0, bw));
        
        vec2  size   = (rect.zw - 1.0) * 0.5;
        vec2  center = gl_FragCoord.xy - (rect.xy + size) + vec2(-0.5);
        float dist   = rbox(center, size, corner_radius);

        float shadow_mul = smoothstep(-6, 6, rbox(center - shadow_offset, size, corner_radius));
        vec4 shadow_mix  = vec4(shadow_final.rgb, shadow.a * (1 - shadow_mul));
        shadow_mix = mix(final, shadow_mix, smoothstep(-1.0, 0.0, dist));
        float dist2       = rbox(center * 1.03, size, corner_radius);
        float rect_mask   = smoothstep(1.0, 0.0, dist);
        float border_mask = smoothstep(bw - 0.5, bw, abs(dist));
        final = mix(final, shadow_mix, smoothstep(0.0, 1.0, dist2));
        final = mix(final, border_color, rect_mask);
        final = mix(final, shadow_mix, border_mask);
        fragColor = final;
    }
    """)
    return gpu.shader.create_from_info(info)


if __name__ == "__main__":
    shader = create_rect_shader_330_plus()
    print("Shader creation successful")
```

**Comment by not-that-nda** [comment]
Shader creation successful

Yes, runs without problems as a script.

**Comment by K-410** [comment]
Thanks for testing. I've implemented and committed a possible fix. Will issue a new release soon.

If you still have issues that are related to shaders, let me know and I'll re-open this.
