### ISSUE TITLE
error install on windows

### ISSUE THREAD

**Issue by hannesdelbeke** [K-410/textension#7]
error when installing on windows 11, Blender 3.2
- downloaded repo as zip
- installed addon
- addon shows up in addon list, but error happens when try to enable it

```
addon_utils.disable: textension-master not disabled
Modules Installed (textension-master) from 'C:\\Users\\hanne\\Downloads\\textension-master.zip' into 'C:\\Users\\hanne\\AppData\\Roaming\\Blender Foundation\\Blender\\3.2\\scripts\\addons'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\modules\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\textension-master\__init__.py", line 21, in <module>
    from . import utils, api, core, overrides, prefs, ui, operators
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\modules\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\textension-master\utils.py", line 617, in <module>
    def redraw_text():
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\textension-master\utils.py", line 62, in inline
    return func(*args, *posonly_args)
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\textension-master\utils.py", line 618, in redraw_text
    from .btypes import ARegion, bContext, byref, get_ARegionType
ImportError: cannot import name 'ARegion' from 'textension-master.btypes' (unknown location)
```

**Comment by hannesdelbeke** [comment]
error when in text editor. and i scroll.
```

WARN (bpy.rna): C:\Users\blender\git\blender-v320\blender.git\source\blender\python\intern\bpy_rna.c:1339 pyrna_enum_to_py: current value '171' matches no enum in 'Event', '(null)', 'type'
Traceback (most recent call last):
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\textension\operators.py", line 359, in modal
    self.accum.unregister(self)
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\textension\operators.py", line 310, in unregister
    ui.remove_draw_hook(ScrollAccumulator.on_redraw)
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\textension\ui\utils.py", line 370, in remove_draw_hook
    handle, hooks = regions[region]
ValueError: not enough values to unpack (expected 2, got 0)
Error: Python: Traceback (most recent call last):
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\textension\operators.py", line 359, in modal
    self.accum.unregister(self)
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\textension\operators.py", line 310, in unregister
    ui.remove_draw_hook(ScrollAccumulator.on_redraw)
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\textension\ui\utils.py", line 370, in remove_draw_hook
    handle, hooks = regions[region]
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by K-410** [comment]
I'd like to try supporting a range of Blender versions so I appreciate any issue reports!

To address your issues:
- Error when installing from archive repo; you need to download from the Releases page for now because dependencies (btypes and Suggestions) are git submodules and in their own repository. I've added a tentative note about this the repository readme.
- The warnings are related to python black magic optimizations. Fixed in commit.
- Errors in the text editor was related to Blender versions below 3.3.0 api change. Fixed in commit.
